server:
  port: 6001

spring:
  application:
    name: micro-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wjonath/config-center.git
      label: master

management:
  security:
    enabled: false
