server:
  port: 6002

ms:
  uri:
    user: ws://micro-user
    blog: ws://micro-blog

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default, Gateway
      routes:
      - id: path-route-user
        uri: ${ms.uri.user}
        predicates:
        - Path=/user/**
        filters:
        - AddResponseHeader=X-Response-User, User-Bar
      - id: path-route-blog
        uri: ${ms.uri.blog}
        predicates:
        - Path=/blog/**
        filters:
        - AddResponseHeader=X-Response-Blog, Blog-Bar

management:
  security:
    enabled: false

debug: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE