server:
  port: 6002

ms:
  uri:
    user: ws://micro-user
    blog: ws://micro-blog
    oauth: ws://micro-oauth

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default, Gateway
      routes:
      - id: path-route-uaa
        uri: ${ms.uri.oauth}
        predicates:
        - Path=/uaa/**
        filters:
        - AddResponseHeader=X-Response-Uaa, Uaa-Bar
      - id: path-route-user
        uri: ${ms.uri.user}
        predicates:
        - Path=/user/**
        filters:
        - AddResponseHeader=X-Response-User, User-Bar
      - id: path-route-blog
        uri: ${ms.uri.blog}
        predicates:
        - Path=/blog/**
        filters:
        - AddResponseHeader=X-Response-Blog, Blog-Bar
  security:
    user:
      password: user

management:
  security:
    enabled: false

debug: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE


security:
  oauth2:
    sso:
      login-path: /login
    client:
      client-id: 625d5ef4fe9dc21708ff
      client-secret: 09528ccc9a12ad5f81be0e71c1fd017ce4044af2
      access-token-uri: http://localhost:8012/oauth/access_token
      user-authorization-uri: http://localhost:8012/oauth/authorize
    resource:
      user-info-uri: https://localhost:8012/user
      prefer-token-info: false