server:
  port: 6002

spring:
  application:
    name: micro-gateway
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
management:
  security:
    enabled: false
debug: true
