management:
  security:
    enabled: false
spring:
  application:
    name: micro-user
  zipkin:
    base-url: http://localhost:8008
  sleuth:
    sampler:
      percentage: 1
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.146.128:9092
          zkNodes: 192.168.146.128:2181
debug: true