management:
  security:
    enabled: false
debug: true

spring:
  application:
    name: micro-user
  zipkin:
    base-url: http://localhost:8008
  sleuth:
    sampler:
      percentage: 1
  cloud:
    stream:
      kafka:
        binder:
          brokers: centos:9092
          zkNodes: centos:2181, localhost:2181
  redis:
    database: 0
    host: centos
    password: ''
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
  activemq:
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
    in-memory: true
    user: system
    password: manager
  data:
    mongodb:
      uri: mongodb://localhost:27017/iqoodb
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/django
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  # 不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false
  mvc:
  # 出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath:mapping/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
